import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { UtulisateurLayoutComponent } from './layout/utulisateur-layout/utulisateur-layout.component';
import { AdminLayoutComponent } from './layout/admin-layout/admin-layout.component';
import { ClientLayoutComponent } from './layout/client-layout/client-layout.component';


const routes: Routes = [
 { path: '', component: UtulisateurLayoutComponent, children: [
   { path: '', loadChildren: () => import('./views/utulisateur/acceuil/acceuil.module').then(m => m.AcceuilModule) },
   { path: 'loginutulisateur', loadChildren: () => import('./views/utulisateur/loginutulisateur/loginutulisateur.module').then(m => m.LoginutulisateurModule) },
   { path: 'inscrireutulisateur', loadChildren: () => import('./views/utulisateur/inscrireutulisateur/inscrireutulisateur.module').then(m => m.InscrireutulisateurModule) },
   { path: 'vehicule', loadChildren: () => import('./views/utulisateur/vehicule/vehicule.module').then(m => m.VehiculeModule)  },
   { path: 'oublier', loadChildren: () => import('./views/utulisateur/oublier/oublier.module').then(m => m.OublierModule)  },

   { path: 'chatbot', loadChildren: () => import('./views/client/chatbot/chatbot.module').then(m => m.ChatbotModule)  },
   { path: 'vehicule/volkswagen', loadChildren: () => import('./views/utulisateur/Modele/volkswagen/volkswagen.module').then(m => m.VolkswagenModule)  },
   { path: 'voiture/volkswagen/golf1', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Volkswagen/golf1/golf1.module').then(m => m.Golf1Module)  },
   { path: 'voiture/volkswagen/golf2', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Volkswagen/golf2/golf2.module').then(m => m.Golf2Module)  },
   { path: 'voiture/volkswagen/golf3', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Volkswagen/golf3/golf3.module').then(m => m.Golf3Module)  },
   { path: 'voiture/volkswagen/golf4', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Volkswagen/golf4/golf4.module').then(m => m.Golf4Module)  },
   { path: 'voiture/volkswagen/golf5', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Volkswagen/golf5/golf5.module').then(m => m.Golf5Module)  },
   { path: 'voiture/volkswagen/golf6', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Volkswagen/golf6/golf6.module').then(m => m.Golf6Module)  },
   { path: 'voiture/volkswagen/golf7', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Volkswagen/golf7/golf7.module').then(m => m.Golf7Module)  },
   { path: 'voiture/volkswagen/golf8', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Volkswagen/golf8/golf8.module').then(m => m.Golf8Module)  },
   { path: 'voiture/volkswagen/tiguan', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Volkswagen/tiguan/tiguan.module').then(m => m.TiguanModule)  },
   { path: 'voiture/volkswagen/passat', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Volkswagen/passat/passat.module').then(m => m.PassatModule)  },
   { path: 'voiture/volkswagen/touareg', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Volkswagen/touareg/touareg.module').then(m => m.TouaregModule)  },
   { path: 'voiture/volkswagen/jeta', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Volkswagen/jeta/jeta.module').then(m => m.JetaModule)  },
   { path: 'voiture/volkswagen/amarok', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Volkswagen/amarok/amarok.module').then(m => m.AmarokModule)  },
   { path: 'vehicule/bmw', loadChildren: () => import('./views/utulisateur/Modele/bmw/bmw.module').then(m => m.BmwModule)  },

   { path: 'vehicule/mercedes', loadChildren: () => import('./views/utulisateur/Modele/mercedes/mercedes.module').then(m => m.MercedesModule)  },
   { path: 'voiture/bmw/x1', loadChildren: () => import('./views/utulisateur/Pieces/voiture/bmw/x1/x1.module').then(m => m.X1Module)  },
   { path: 'voiture/bmw/x2', loadChildren: () => import('./views/utulisateur/Pieces/voiture/bmw/x2/x2.module').then(m => m.X2Module)  },
   { path: 'voiture/bmw/x3', loadChildren: () => import('./views/utulisateur/Pieces/voiture/bmw/x3/x3.module').then(m => m.X3Module)  },
   { path: 'voiture/bmw/x4', loadChildren: () => import('./views/utulisateur/Pieces/voiture/bmw/x4/x4.module').then(m => m.X4Module)  },
   { path: 'voiture/bmw/x5', loadChildren: () => import('./views/utulisateur/Pieces/voiture/bmw/x5/x5.module').then(m => m.X5Module)  },
   { path: 'voiture/bmw/serie6', loadChildren: () => import('./views/utulisateur/Pieces/voiture/bmw/serie6/serie6.module').then(m => m.Serie6Module)  },
   { path: 'voiture/mercedes/gla', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Mercedes/gla/gla.module').then(m => m.GlaModule)  },
   { path: 'voiture/mercedes/glc', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Mercedes/glc/glc.module').then(m => m.GlcModule)  },
   { path: 'voiture/mercedes/classe-a', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Mercedes/classe-a/classe-a.module').then(m => m.ClasseAModule)  },
   { path: 'voiture/mercedes/classe-s', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Mercedes/classe-s/classe-s.module').then(m => m.ClasseSModule)  },
   { path: 'voiture/mercedes/classe-g', loadChildren: () => import('./views/utulisateur/Pieces/voiture/Mercedes/classe-g/classe-g.module').then(m => m.ClasseGModule)  },
   { path: 'vehicule/seat', loadChildren: () => import('./views/utulisateur/Modele/seat/seat.module').then(m => m.SeatModule)  },
   { path: 'voiture/seat/ibiza', loadChildren: () => import('./views/utulisateur/Pieces/voiture/seat/ibiza/ibiza.module').then(m => m.IbizaModule)  },
   { path: 'voiture/seat/leon', loadChildren: () => import('./views/utulisateur/Pieces/voiture/seat/leon/leon.module').then(m => m.LeonModule)  },
   { path: 'voiture/seat/arona', loadChildren: () => import('./views/utulisateur/Pieces/voiture/seat/arona/arona.module').then(m => m.AronaModule)  },
   { path: 'voiture/seat/ateca', loadChildren: () => import('./views/utulisateur/Pieces/voiture/seat/ateca/ateca.module').then(m => m.AtecaModule)  },
   { path: 'vehicule/skoda', loadChildren: () => import('./views/utulisateur/Modele/skoda/skoda.module').then(m => m.SkodaModule)  },
   { path: 'vehicule/renault', loadChildren: () => import('./views/utulisateur/Modele/renault/renault.module').then(m => m.RenaultModule)  },
   { path: 'vehicule/fiat', loadChildren: () => import('./views/utulisateur/Modele/fiat/fiat.module').then(m => m.FiatModule)  },
   { path: 'vehicule/kia', loadChildren: () => import('./views/utulisateur/Modele/kia/kia.module').then(m => m.KiaModule)  },

   { path: 'vehicule/toyota', loadChildren: () => import('./views/utulisateur/Modele/toyota/toyota.module').then(m => m.ToyotaModule)  },
   { path: 'vehicule/audi', loadChildren: () => import('./views/utulisateur/Modele/audi/audi.module').then(m => m.AudiModule)  },
   { path: 'vehicule/citroen', loadChildren: () => import('./views/utulisateur/Modele/citroen/citroen.module').then(m => m.CitroenModule)  },
   { path: 'vehicule/hyundai', loadChildren: () => import('./views/utulisateur/Modele/hyundai/hyundai.module').then(m => m.HyundaiModule)  },
   { path: 'vehicule/peugeot', loadChildren: () => import('./views/utulisateur/Modele/peugeot/peugeot.module').then(m => m.PeugeotModule)  },
   { path: 'vehicule/honda', loadChildren: () => import('./views/utulisateur/Modele/honda/honda.module').then(m => m.HondaModule)  },
   { path: 'vehicule/ssangyong', loadChildren: () => import('./views/utulisateur/Modele/ssangyong/ssangyong.module').then(m => m.SsangyongModule)  },
   { path: 'voiture/skoda/fabia', loadChildren: () => import('./views/utulisateur/Pieces/voiture/skoda/fabia/fabia.module').then(m => m.FabiaModule)  },
   { path: 'voiture/skoda/kodiaq', loadChildren: () => import('./views/utulisateur/Pieces/voiture/skoda/kodiaq/kodiaq.module').then(m => m.KodiaqModule)  },
   { path: 'voiture/skoda/kushaq', loadChildren: () => import('./views/utulisateur/Pieces/voiture/skoda/kushaq/kushaq.module').then(m => m.KushaqModule)  },
   { path: 'voiture/skoda/superb', loadChildren: () => import('./views/utulisateur/Pieces/voiture/skoda/superb/superb.module').then(m => m.SuperbModule)  },
   { path: 'voiture/renault/symbole', loadChildren: () => import('./views/utulisateur/Pieces/voiture/reanult/symbole/symbole.module').then(m => m.SymboleModule)  },
   { path: 'voiture/renault/cliocampus', loadChildren: () => import('./views/utulisateur/Pieces/voiture/reanult/cliocampus/cliocampus.module').then(m => m.CliocampusModule)  },
   { path: 'voiture/renault/clio3', loadChildren: () => import('./views/utulisateur/Pieces/voiture/reanult/clio3/clio3.module').then(m => m.Clio3Module)  },
   { path: 'voiture/renault/cliodynamique', loadChildren: () => import('./views/utulisateur/Pieces/voiture/reanult/cliodynamique/cliodynamique.module').then(m => m.CliodynamiqueModule)  },
   { path: 'voiture/renault/megane', loadChildren: () => import('./views/utulisateur/Pieces/voiture/reanult/megane/megane.module').then(m => m.MeganeModule)  },
   { path: 'voiture/peugeot/206', loadChildren: () => import('./views/utulisateur/Pieces/voiture/peugeot/p206/p206.module').then(m => m.P206Module)  },
   { path: 'voiture/peugeot/308', loadChildren: () => import('./views/utulisateur/Pieces/voiture/peugeot/p308/p308.module').then(m => m.P308Module)  },
   { path: 'voiture/peugeot/408', loadChildren: () => import('./views/utulisateur/Pieces/voiture/peugeot/p408/p408.module').then(m => m.P408Module)  },

   { path: 'voiture/peugeot/3008', loadChildren: () => import('./views/utulisateur/Pieces/voiture/peugeot/p3008/p3008.module').then(m => m.P3008Module)  },
   { path: 'voiture/fiat/500', loadChildren: () => import('./views/utulisateur/Pieces/voiture/fiat/f500/f500.module').then(m => m.F500Module)  },
   { path: 'voiture/fiat/fiorino', loadChildren: () => import('./views/utulisateur/Pieces/voiture/fiat/fiorino/fiorino.module').then(m => m.FiorinoModule)  },
   { path: 'voiture/fiat/panda', loadChildren: () => import('./views/utulisateur/Pieces/voiture/fiat/panda/panda.module').then(m => m.PandaModule)  },
   { path: 'voiture/fiat/punto', loadChildren: () => import('./views/utulisateur/Pieces/voiture/fiat/punto/punto.module').then(m => m.PuntoModule)  },
   { path: 'voiture/fiat/tipo', loadChildren: () => import('./views/utulisateur/Pieces/voiture/fiat/tipo/tipo.module').then(m => m.TipoModule)  },
   { path: 'voiture/kia/rio', loadChildren: () => import('./views/utulisateur/Pieces/voiture/kia/rio/rio.module').then(m => m.RioModule)  },
   { path: 'voiture/kia/xceed', loadChildren: () => import('./views/utulisateur/Pieces/voiture/kia/xceed/xceed.module').then(m => m.XceedModule)  },
   { path: 'voiture/kia/sportage', loadChildren: () => import('./views/utulisateur/Pieces/voiture/kia/sportage/sportage.module').then(m => m.SportageModule)  },
   { path: 'voiture/kia/sorento', loadChildren: () => import('./views/utulisateur/Pieces/voiture/kia/sorento/sorento.module').then(m => m.SorentoModule)  },
   { path: 'voiture/toyota/rav4', loadChildren: () => import('./views/utulisateur/Pieces/voiture/toyota/rav4/rav4.module').then(m => m.Rav4Module)  },
   { path: 'voiture/toyota/yaris', loadChildren: () => import('./views/utulisateur/Pieces/voiture/toyota/yaris/yaris.module').then(m => m.YarisModule)  },
   { path: 'voiture/toyota/aygo', loadChildren: () => import('./views/utulisateur/Pieces/voiture/toyota/aygo/aygo.module').then(m => m.AygoModule)  },
   { path: 'voiture/toyota/hilux', loadChildren: () => import('./views/utulisateur/Pieces/voiture/toyota/hilux/hilux.module').then(m => m.HiluxModule)  },
   { path: 'voiture/toyota/chr', loadChildren: () => import('./views/utulisateur/Pieces/voiture/toyota/chr/chr.module').then(m => m.ChrModule)  },
   { path: 'voiture/audi/a3', loadChildren: () => import('./views/utulisateur/Pieces/voiture/audi/a3/a3.module').then(m => m.A3Module)  },
   { path: 'voiture/audi/a4', loadChildren: () => import('./views/utulisateur/Pieces/voiture/audi/a4/a4.module').then(m => m.A4Module)  },
   { path: 'voiture/audi/a6', loadChildren: () => import('./views/utulisateur/Pieces/voiture/audi/a6/a6.module').then(m => m.A6Module)  },
   { path: 'voiture/audi/q5', loadChildren: () => import('./views/utulisateur/Pieces/voiture/audi/q5/q5.module').then(m => m.Q5Module)  },
   { path: 'voiture/citoren/berlingo', loadChildren: () => import('./views/utulisateur/Pieces/voiture/citroen/berlingo/berlingo.module').then(m => m.BerlingoModule)  },
   { path: 'voiture/citoren/celysee', loadChildren: () => import('./views/utulisateur/Pieces/voiture/citroen/celysee/celysee.module').then(m => m.CelyseeModule)  },
   { path: 'voiture/citoren/c3', loadChildren: () => import('./views/utulisateur/Pieces/voiture/citroen/c3/c3.module').then(m => m.C3Module)  },
   { path: 'voiture/citoren/c5', loadChildren: () => import('./views/utulisateur/Pieces/voiture/citroen/c5/c5.module').then(m => m.C5Module)  },
   { path: 'voiture/hyundai/i10', loadChildren: () => import('./views/utulisateur/Pieces/voiture/hyundai/i10/i10.module').then(m => m.I10Module)  },
   { path: 'voiture/hyundai/i20', loadChildren: () => import('./views/utulisateur/Pieces/voiture/hyundai/i20/i20.module').then(m => m.I20Module)  },
   { path: 'voiture/honda/city', loadChildren: () => import('./views/utulisateur/Pieces/voiture/honda/city/city.module').then(m => m.CityModule)  },

   { path: 'voiture/honda/crv', loadChildren: () => import('./views/utulisateur/Pieces/voiture/honda/crv/crv.module').then(m => m.CrvModule)  },
   { path: 'voiture/ssangyong/korando', loadChildren: () => import('./views/utulisateur/Pieces/voiture/ssangyong/korando/korando.module').then(m => m.KorandoModule)  },
   { path: 'voiture/ssangyong/musso', loadChildren: () => import('./views/utulisateur/Pieces/voiture/ssangyong/musso/musso.module').then(m => m.MussoModule)  },
   { path: 'voiture/ssangyong/rexton', loadChildren: () => import('./views/utulisateur/Pieces/voiture/ssangyong/rexton/rexton.module').then(m => m.RextonModule)  },
   { path: 'voiture/ssangyong/trivoli', loadChildren: () => import('./views/utulisateur/Pieces/voiture/ssangyong/trivoli/trivoli.module').then(m => m.TrivoliModule)  },
   { path: 'voiture/volkswagen/golf1/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/volkswagen/golf1/golf1.module').then(m => m.Golf1Module)  },
   { path: 'voiture/volkswagen/golf2/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/volkswagen/golf2/golf2.module').then(m => m.Golf2Module)  },
   { path: 'voiture/volkswagen/golf3/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/volkswagen/golf3/golf3.module').then(m => m.Golf3Module)  },
   { path: 'voiture/volkswagen/golf4/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/volkswagen/golf4/golf4.module').then(m => m.Golf4Module)  },
   { path: 'voiture/volkswagen/golf5/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/volkswagen/golf5/golf5.module').then(m => m.Golf5Module)  },
   { path: 'voiture/volkswagen/golf6/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/volkswagen/golf6/golf6.module').then(m => m.Golf6Module)  },
   { path: 'voiture/volkswagen/golf7/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/volkswagen/golf7/golf7.module').then(m => m.Golf7Module)  },
   { path: 'voiture/volkswagen/golf8/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/volkswagen/golf8/golf8.module').then(m => m.Golf8Module)  },
   { path: 'voiture/volkswagen/amarok/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/volkswagen/amarok/amarok.module').then(m => m.AmarokModule)  },
   { path: 'voiture/volkswagen/jeta/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/volkswagen/jeta/jeta.module').then(m => m.JetaModule)  },
   { path: 'voiture/volkswagen/touareg/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/volkswagen/touareg/touareg.module').then(m => m.TouaregModule)  },
   { path: 'voiture/volkswagen/passat/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/volkswagen/passat/passat.module').then(m => m.PassatModule)  },
   { path: 'voiture/volkswagen/tiguan/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/volkswagen/tiguan/tiguan.module').then(m => m.TiguanModule)  },
   { path: 'voiture/bmw/serie6/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/bmw/serie6/serie6.module').then(m => m.Serie6Module)  },
   { path: 'voiture/bmw/x1/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/bmw/x1/x1.module').then(m => m.X1Module)  },
   { path: 'voiture/bmw/x2/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/bmw/x2/x2.module').then(m => m.X2Module)  },
   { path: 'voiture/bmw/x3/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/bmw/x3/x3.module').then(m => m.X3Module)  },
   { path: 'voiture/bmw/x4/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/bmw/x4/x4.module').then(m => m.X4Module)  },
   { path: 'voiture/bmw/x5/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/bmw/x5/x5.module').then(m => m.X5Module)  },
   { path: 'voiture/mercedes/gla/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/mercedes/gla/gla.module').then(m => m.GlaModule)  },
   { path: 'voiture/mercedes/glc/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/mercedes/glc/glc.module').then(m => m.GlcModule)  },
   { path: 'voiture/mercedes/classea/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/mercedes/classea/classea.module').then(m => m.ClasseaModule)  },
   { path: 'voiture/mercedes/classeg/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/mercedes/classeg/classeg.module').then(m => m.ClassegModule)  },
   { path: 'voiture/mercedes/classes/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/mercedes/classes/classes.module').then(m => m.ClassesModule)  },
   { path: 'voiture/seat/ateca/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/seat/ateca/ateca.module').then(m => m.AtecaModule)  },
   { path: 'voiture/seat/arona/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/seat/arona/arona.module').then(m => m.AronaModule)  },
   { path: 'voiture/seat/ibiza/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/seat/ibiza/ibiza.module').then(m => m.IbizaModule)  },
   { path: 'voiture/seat/leon/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/seat/leon/leon.module').then(m => m.LeonModule)  },
   { path: 'voiture/skoda/superb/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/skoda/superb/superb.module').then(m => m.SuperbModule)  },
   { path: 'voiture/skoda/kushaq/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/skoda/kushaq/kushaq.module').then(m => m.KushaqModule)  },
   { path: 'voiture/skoda/kodiaq/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/skoda/kodiaq/kodiaq.module').then(m => m.KodiaqModule)  },
   { path: 'voiture/skoda/fabia/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/skoda/fabia/fabia.module').then(m => m.FabiaModule)  },
   { path: 'voiture/renault/cliocampus/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/renault/cliocampus/cliocampus.module').then(m => m.CliocampusModule)  },
   { path: 'voiture/renault/cliodynamique/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/renault/cliodynamique/cliodynamique.module').then(m => m.CliodynamiqueModule)  },
   { path: 'voiture/renault/megane/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/renault/megane/megane.module').then(m => m.MeganeModule)  },
   { path: 'voiture/renault/symbole/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/renault/symbole/symbole.module').then(m => m.SymboleModule)  },
   { path: 'voiture/renault/clio3/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/renault/clio3/clio3.module').then(m => m.Clio3Module)  },
   { path: 'voiture/peugeot/p206/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/peugeot/p206/p206.module').then(m => m.P206Module)  },
   { path: 'voiture/peugeot/p308/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/peugeot/p308/p308.module').then(m => m.P308Module)  },

   { path: 'voiture/peugeot/p408/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/peugeot/p408/p408.module').then(m => m.P408Module)  },
   { path: 'voiture/peugeot/p3008/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/peugeot/p3008/p3008.module').then(m => m.P3008Module)  },
   { path: 'voiture/fiat/tipo/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/fiat/tipo/tipo.module').then(m => m.TipoModule)  },
   { path: 'voiture/fiat/punto/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/fiat/punto/punto.module').then(m => m.PuntoModule)  },
   { path: 'voiture/fiat/panda/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/fiat/panda/panda.module').then(m => m.PandaModule)  },
   { path: 'voiture/fiat/fiorino/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/fiat/fiorino/fiorino.module').then(m => m.FiorinoModule)  },
   { path: 'voiture/fiat/f500/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/fiat/f500/f500.module').then(m => m.F500Module)  },
   { path: 'voiture/kia/sorento/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/kia/sorento/sorento.module').then(m => m.SorentoModule)  },
   { path: 'voiture/kia/xceed/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/kia/xceed/xceed.module').then(m => m.XceedModule)  },
   { path: 'voiture/kia/sportage/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/kia/sportage/sportage.module').then(m => m.SportageModule)  },
   { path: 'voiture/kia/rio/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/kia/rio/rio.module').then(m => m.RioModule)  },
   { path: 'voiture/toyota/aygo/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/toyota/aygo/aygo.module').then(m => m.AygoModule)  },
   { path: 'voiture/toyota/rav4/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/toyota/rav4/rav4.module').then(m => m.Rav4Module)  },
   { path: 'voiture/toyota/yaris/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/toyota/yaris/yaris.module').then(m => m.YarisModule)  },
   { path: 'voiture/toyota/hilux/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/toyota/hilux/hilux.module').then(m => m.HiluxModule)  },
   { path: 'voiture/toyota/chr/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/toyota/chr/chr.module').then(m => m.ChrModule)  },
   { path: 'voiture/audi/q5/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/audi/q5/q5.module').then(m => m.Q5Module)  },
   { path: 'voiture/audi/a4/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/audi/a4/a4.module').then(m => m.A4Module)  },
   { path: 'voiture/audi/a6/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/audi/a6/a6.module').then(m => m.A6Module)  },
   { path: 'voiture/audi/a3/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/audi/a3/a3.module').then(m => m.A3Module)  },
   { path: 'voiture/citroen/c5/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/citroen/c5/c5.module').then(m => m.C5Module)  },
   { path: 'voiture/citroen/celysee/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/citroen/celysee/celysee.module').then(m => m.CelyseeModule)  },

   { path: 'voiture/citroen/berlingo/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/citroen/berlingo/berlingo.module').then(m => m.BerlingoModule)  },
   { path: 'voiture/citroen/c3/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/citroen/c3/c3.module').then(m => m.C3Module)  },
   { path: 'voiture/hyundai/i10/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/hyundai/i10/i10.module').then(m => m.I10Module)  },
   { path: 'voiture/hyundai/i20/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/hyundai/i20/i20.module').then(m => m.I20Module)  },
   { path: 'voiture/honda/city/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/honda/city/city.module').then(m => m.CityModule)  },
   { path: 'voiture/honda/crv/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/honda/crv/crv.module').then(m => m.CrvModule)  },
   { path: 'voiture/ssangyong/korando/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/ssangyong/korando/korando.module').then(m => m.KorandoModule)  },
   { path: 'voiture/ssangyong/rexton/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/ssangyong/rexton/rexton.module').then(m => m.RextonModule)  },
   { path: 'voiture/ssangyong/musso/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/ssangyong/musso/musso.module').then(m => m.MussoModule)  },
   { path: 'voiture/ssangyong/trivoli/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/voiture/ssangyong/trivoli/trivoli.module').then(m => m.TrivoliModule)  },
   { path: 'moto', loadChildren: () => import('./views/utulisateur/moto/moto.module').then(m => m.MotoModule)  },
   { path: 'moto/yamaha', loadChildren: () => import('./views/utulisateur/Modele/yamaha/yamaha.module').then(m => m.YamahaModule)  },
   { path: 'moto/kawasaki', loadChildren: () => import('./views/utulisateur/Modele/kawasaki/kawasaki.module').then(m => m.KawasakiModule)  },
   { path: 'moto/yamaha/mt03', loadChildren: () => import('./views/utulisateur/Pieces/moto/yamaha/mt03/mt03.module').then(m => m.Mt03Module)  },
   { path: 'moto/yamaha/tmax', loadChildren: () => import('./views/utulisateur/Pieces/moto/yamaha/tmax/tmax.module').then(m => m.TmaxModule)  },
   { path: 'moto/yamaha/mt03/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/moto/yamaha/mt03/mt03.module').then(m => m.Mt03Module)  },
   { path: 'moto/yamaha/tmax/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/moto/yamaha/tmax/tmax.module').then(m => m.TmaxModule)  },
   { path: 'moto/kawasaki/z1000', loadChildren: () => import('./views/utulisateur/Pieces/moto/kawasaki/z1000/z1000.module').then(m => m.Z1000Module)  },
   { path: 'moto/kawasaki/z750', loadChildren: () => import('./views/utulisateur/Pieces/moto/kawasaki/z750/z750.module').then(m => m.Z750Module)  },
   { path: 'moto/kawasaki/z1000/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/moto/kawasaki/z1000/z1000.module').then(m => m.Z1000Module)  },
   { path: 'moto/kawasaki/z750/pieces/:id', loadChildren: () => import('./views/utulisateur/detaillep/moto/kawasaki/z750/z750.module').then(m => m.Z750Module)  },











 ]},
 { path: 'admin', component: AdminLayoutComponent, children: [
  { path: '', loadChildren: () => import('./views/admin/loginadmin/loginadmin.module').then(m => m.LoginadminModule) },
   { path: 'dashboard', loadChildren: () => import('./views/admin/dashboard/dashboard.module').then(m => m.DashboardModule) },
   { path: 'acceuiladmin', loadChildren: () => import('./views/admin/acceuiladmin/acceuiladmin.module').then(m => m.AcceuiladminModule) },
   { path: 'pieces', loadChildren: () => import('./views/admin/pieces/pieces.module').then(m => m.PiecesModule) },
   { path: 'admint', loadChildren: () => import('./views/admin/admint/admint.module').then(m => m.AdmintModule) },
   { path: 'tachat', loadChildren: () => import('./views/admin/tachat/tachat.module').then(m => m.TachatModule) },



 ]},






 


 { path: 'client', component: ClientLayoutComponent, children:[
   { path: '', loadChildren: () => import('./views/client/acceuil/acceuil.module').then(m => m.AcceuilModule) },
   { path: 'profil', loadChildren: () => import('./views/client/profil/profil.module').then(m => m.ProfilModule) },
   { path: 'vehicule', loadChildren: () => import('./views/client/vehicule/vehicule.module').then(m => m.VehiculeModule)  },
   { path: 'panier', loadChildren: () => import('./views/client/panier/panier.module').then(m => m.PanierModule)  },
   { path: 'chatbot', loadChildren: () => import('./views/client/chatbot/chatbot.module').then(m => m.ChatbotModule)  },
   { path: 'achat', loadChildren: () => import('./views/client/achat/achat.module').then(m => m.AchatModule)  },

   { path: 'vehicule/volkswagen', loadChildren: () => import('./views/client/Modele/volkswagen/volkswagen.module').then(m => m.VolkswagenModule)  },
   { path: 'voiture/volkswagen/golf1', loadChildren: () => import('./views/client/Pieces/voiture/Volkswagen/golf1/golf1.module').then(m => m.Golf1Module)  },
   { path: 'voiture/volkswagen/golf2', loadChildren: () => import('./views/client/Pieces/voiture/Volkswagen/golf2/golf2.module').then(m => m.Golf2Module)  },
   { path: 'voiture/volkswagen/golf3', loadChildren: () => import('./views/client/Pieces/voiture/Volkswagen/golf3/golf3.module').then(m => m.Golf3Module)  },
   { path: 'voiture/volkswagen/golf4', loadChildren: () => import('./views/client/Pieces/voiture/Volkswagen/golf4/golf4.module').then(m => m.Golf4Module)  },
   { path: 'voiture/volkswagen/golf5', loadChildren: () => import('./views/client/Pieces/voiture/Volkswagen/golf5/golf5.module').then(m => m.Golf5Module)  },
   { path: 'voiture/volkswagen/golf6', loadChildren: () => import('./views/client/Pieces/voiture/Volkswagen/golf6/golf6.module').then(m => m.Golf6Module)  },
   { path: 'voiture/volkswagen/golf7', loadChildren: () => import('./views/client/Pieces/voiture/Volkswagen/golf7/golf7.module').then(m => m.Golf7Module)  },
   { path: 'voiture/volkswagen/golf8', loadChildren: () => import('./views/client/Pieces/voiture/Volkswagen/golf8/golf8.module').then(m => m.Golf8Module)  },
   { path: 'voiture/volkswagen/tiguan', loadChildren: () => import('./views/client/Pieces/voiture/Volkswagen/tiguan/tiguan.module').then(m => m.TiguanModule)  },
   { path: 'voiture/volkswagen/passat', loadChildren: () => import('./views/client/Pieces/voiture/Volkswagen/passat/passat.module').then(m => m.PassatModule)  },
   { path: 'voiture/volkswagen/touareg', loadChildren: () => import('./views/client/Pieces/voiture/Volkswagen/touareg/touareg.module').then(m => m.TouaregModule)  },
   { path: 'voiture/volkswagen/jeta', loadChildren: () => import('./views/client/Pieces/voiture/Volkswagen/jeta/jeta.module').then(m => m.JetaModule)  },
   { path: 'voiture/volkswagen/amarok', loadChildren: () => import('./views/client/Pieces/voiture/Volkswagen/amarok/amarok.module').then(m => m.AmarokModule)  },
   { path: 'vehicule/bmw', loadChildren: () => import('./views/client/Modele/bmw/bmw.module').then(m => m.BmwModule)  },

   { path: 'vehicule/mercedes', loadChildren: () => import('./views/client/Modele/mercedes/mercedes.module').then(m => m.MercedesModule)  },
   { path: 'voiture/bmw/x1', loadChildren: () => import('./views/client/Pieces/voiture/bmw/x1/x1.module').then(m => m.X1Module)  },
   { path: 'voiture/bmw/x2', loadChildren: () => import('./views/client/Pieces/voiture/bmw/x2/x2.module').then(m => m.X2Module)  },
   { path: 'voiture/bmw/x3', loadChildren: () => import('./views/client/Pieces/voiture/bmw/x3/x3.module').then(m => m.X3Module)  },
   { path: 'voiture/bmw/x4', loadChildren: () => import('./views/client/Pieces/voiture/bmw/x4/x4.module').then(m => m.X4Module)  },
   { path: 'voiture/bmw/x5', loadChildren: () => import('./views/client/Pieces/voiture/bmw/x5/x5.module').then(m => m.X5Module)  },
   { path: 'voiture/bmw/serie6', loadChildren: () => import('./views/client/Pieces/voiture/bmw/serie6/serie6.module').then(m => m.Serie6Module)  },
   { path: 'voiture/mercedes/gla', loadChildren: () => import('./views/client/Pieces/voiture/Mercedes/gla/gla.module').then(m => m.GlaModule)  },
   { path: 'voiture/mercedes/glc', loadChildren: () => import('./views/client/Pieces/voiture/Mercedes/glc/glc.module').then(m => m.GlcModule)  },
   { path: 'voiture/mercedes/classe-a', loadChildren: () => import('./views/client/Pieces/voiture/Mercedes/classe-a/classe-a.module').then(m => m.ClasseAModule)  },
   { path: 'voiture/mercedes/classe-s', loadChildren: () => import('./views/client/Pieces/voiture/Mercedes/classe-s/classe-s.module').then(m => m.ClasseSModule)  },
   { path: 'voiture/mercedes/classe-g', loadChildren: () => import('./views/client/Pieces/voiture/Mercedes/classe-g/classe-g.module').then(m => m.ClasseGModule)  },
   { path: 'vehicule/seat', loadChildren: () => import('./views/client/Modele/seat/seat.module').then(m => m.SeatModule)  },
   { path: 'voiture/seat/ibiza', loadChildren: () => import('./views/client/Pieces/voiture/seat/ibiza/ibiza.module').then(m => m.IbizaModule)  },
   { path: 'voiture/seat/leon', loadChildren: () => import('./views/client/Pieces/voiture/seat/leon/leon.module').then(m => m.LeonModule)  },
   { path: 'voiture/seat/arona', loadChildren: () => import('./views/client/Pieces/voiture/seat/arona/arona.module').then(m => m.AronaModule)  },
   { path: 'voiture/seat/ateca', loadChildren: () => import('./views/client/Pieces/voiture/seat/ateca/ateca.module').then(m => m.AtecaModule)  },
   { path: 'vehicule/skoda', loadChildren: () => import('./views/client/Modele/skoda/skoda.module').then(m => m.SkodaModule)  },
   { path: 'vehicule/renault', loadChildren: () => import('./views/client/Modele/renault/renault.module').then(m => m.RenaultModule)  },
   { path: 'vehicule/fiat', loadChildren: () => import('./views/client/Modele/fiat/fiat.module').then(m => m.FiatModule)  },
   { path: 'vehicule/kia', loadChildren: () => import('./views/client/Modele/kia/kia.module').then(m => m.KiaModule)  },

   { path: 'vehicule/toyota', loadChildren: () => import('./views/client/Modele/toyota/toyota.module').then(m => m.ToyotaModule)  },
   { path: 'vehicule/audi', loadChildren: () => import('./views/client/Modele/audi/audi.module').then(m => m.AudiModule)  },
   { path: 'vehicule/citroen', loadChildren: () => import('./views/client/Modele/citroen/citroen.module').then(m => m.CitroenModule)  },
   { path: 'vehicule/hyundai', loadChildren: () => import('./views/client/Modele/hyundai/hyundai.module').then(m => m.HyundaiModule)  },
   { path: 'vehicule/peugeot', loadChildren: () => import('./views/client/Modele/peugeot/peugeot.module').then(m => m.PeugeotModule)  },
   { path: 'vehicule/honda', loadChildren: () => import('./views/client/Modele/honda/honda.module').then(m => m.HondaModule)  },
   { path: 'vehicule/ssangyong', loadChildren: () => import('./views/client/Modele/ssangyong/ssangyong.module').then(m => m.SsangyongModule)  },
   { path: 'voiture/skoda/fabia', loadChildren: () => import('./views/client/Pieces/voiture/skoda/fabia/fabia.module').then(m => m.FabiaModule)  },
   { path: 'voiture/skoda/kodiaq', loadChildren: () => import('./views/client/Pieces/voiture/skoda/kodiaq/kodiaq.module').then(m => m.KodiaqModule)  },
   { path: 'voiture/skoda/kushaq', loadChildren: () => import('./views/client/Pieces/voiture/skoda/kushaq/kushaq.module').then(m => m.KushaqModule)  },
   { path: 'voiture/skoda/superb', loadChildren: () => import('./views/client/Pieces/voiture/skoda/superb/superb.module').then(m => m.SuperbModule)  },
   { path: 'voiture/renault/symbole', loadChildren: () => import('./views/client/Pieces/voiture/reanult/symbole/symbole.module').then(m => m.SymboleModule)  },
   { path: 'voiture/renault/cliocampus', loadChildren: () => import('./views/client/Pieces/voiture/reanult/cliocampus/cliocampus.module').then(m => m.CliocampusModule)  },
   { path: 'voiture/renault/clio3', loadChildren: () => import('./views/client/Pieces/voiture/reanult/clio3/clio3.module').then(m => m.Clio3Module)  },
   { path: 'voiture/renault/cliodynamique', loadChildren: () => import('./views/client/Pieces/voiture/reanult/cliodynamique/cliodynamique.module').then(m => m.CliodynamiqueModule)  },
   { path: 'voiture/renault/megane', loadChildren: () => import('./views/client/Pieces/voiture/reanult/megane/megane.module').then(m => m.MeganeModule)  },
   { path: 'voiture/peugeot/206', loadChildren: () => import('./views/client/Pieces/voiture/peugeot/p206/p206.module').then(m => m.P206Module)  },
   { path: 'voiture/peugeot/308', loadChildren: () => import('./views/client/Pieces/voiture/peugeot/p308/p308.module').then(m => m.P308Module)  },
   { path: 'voiture/peugeot/408', loadChildren: () => import('./views/client/Pieces/voiture/peugeot/p408/p408.module').then(m => m.P408Module)  },

   { path: 'voiture/peugeot/3008', loadChildren: () => import('./views/client/Pieces/voiture/peugeot/p3008/p3008.module').then(m => m.P3008Module)  },
   { path: 'voiture/fiat/500', loadChildren: () => import('./views/client/Pieces/voiture/fiat/f500/f500.module').then(m => m.F500Module)  },
   { path: 'voiture/fiat/fiorino', loadChildren: () => import('./views/client/Pieces/voiture/fiat/fiorino/fiorino.module').then(m => m.FiorinoModule)  },
   { path: 'voiture/fiat/panda', loadChildren: () => import('./views/client/Pieces/voiture/fiat/panda/panda.module').then(m => m.PandaModule)  },
   { path: 'voiture/fiat/punto', loadChildren: () => import('./views/client/Pieces/voiture/fiat/punto/punto.module').then(m => m.PuntoModule)  },
   { path: 'voiture/fiat/tipo', loadChildren: () => import('./views/client/Pieces/voiture/fiat/tipo/tipo.module').then(m => m.TipoModule)  },
   { path: 'voiture/kia/rio', loadChildren: () => import('./views/client/Pieces/voiture/kia/rio/rio.module').then(m => m.RioModule)  },
   { path: 'voiture/kia/xceed', loadChildren: () => import('./views/client/Pieces/voiture/kia/xceed/xceed.module').then(m => m.XceedModule)  },
   { path: 'voiture/kia/sportage', loadChildren: () => import('./views/client/Pieces/voiture/kia/sportage/sportage.module').then(m => m.SportageModule)  },
   { path: 'voiture/kia/sorento', loadChildren: () => import('./views/client/Pieces/voiture/kia/sorento/sorento.module').then(m => m.SorentoModule)  },
   { path: 'voiture/toyota/rav4', loadChildren: () => import('./views/client/Pieces/voiture/toyota/rav4/rav4.module').then(m => m.Rav4Module)  },
   { path: 'voiture/toyota/yaris', loadChildren: () => import('./views/client/Pieces/voiture/toyota/yaris/yaris.module').then(m => m.YarisModule)  },
   { path: 'voiture/toyota/aygo', loadChildren: () => import('./views/client/Pieces/voiture/toyota/aygo/aygo.module').then(m => m.AygoModule)  },
   { path: 'voiture/toyota/hilux', loadChildren: () => import('./views/client/Pieces/voiture/toyota/hilux/hilux.module').then(m => m.HiluxModule)  },
   { path: 'voiture/toyota/chr', loadChildren: () => import('./views/client/Pieces/voiture/toyota/chr/chr.module').then(m => m.ChrModule)  },
   { path: 'voiture/audi/a3', loadChildren: () => import('./views/client/Pieces/voiture/audi/a3/a3.module').then(m => m.A3Module)  },
   { path: 'voiture/audi/a4', loadChildren: () => import('./views/client/Pieces/voiture/audi/a4/a4.module').then(m => m.A4Module)  },
   { path: 'voiture/audi/a6', loadChildren: () => import('./views/client/Pieces/voiture/audi/a6/a6.module').then(m => m.A6Module)  },
   { path: 'voiture/audi/q5', loadChildren: () => import('./views/client/Pieces/voiture/audi/q5/q5.module').then(m => m.Q5Module)  },
   { path: 'voiture/citoren/berlingo', loadChildren: () => import('./views/client/Pieces/voiture/citroen/berlingo/berlingo.module').then(m => m.BerlingoModule)  },
   { path: 'voiture/citoren/celysee', loadChildren: () => import('./views/client/Pieces/voiture/citroen/celysee/celysee.module').then(m => m.CelyseeModule)  },
   { path: 'voiture/citoren/c3', loadChildren: () => import('./views/client/Pieces/voiture/citroen/c3/c3.module').then(m => m.C3Module)  },
   { path: 'voiture/citoren/c5', loadChildren: () => import('./views/client/Pieces/voiture/citroen/c5/c5.module').then(m => m.C5Module)  },
   { path: 'voiture/hyundai/i10', loadChildren: () => import('./views/client/Pieces/voiture/hyundai/i10/i10.module').then(m => m.I10Module)  },
   { path: 'voiture/hyundai/i20', loadChildren: () => import('./views/client/Pieces/voiture/hyundai/i20/i20.module').then(m => m.I20Module)  },
   { path: 'voiture/honda/city', loadChildren: () => import('./views/client/Pieces/voiture/honda/city/city.module').then(m => m.CityModule)  },

   { path: 'voiture/honda/crv', loadChildren: () => import('./views/client/Pieces/voiture/honda/crv/crv.module').then(m => m.CrvModule)  },
   { path: 'voiture/ssangyong/korando', loadChildren: () => import('./views/client/Pieces/voiture/ssangyong/korando/korando.module').then(m => m.KorandoModule)  },
   { path: 'voiture/ssangyong/musso', loadChildren: () => import('./views/client/Pieces/voiture/ssangyong/musso/musso.module').then(m => m.MussoModule)  },
   { path: 'voiture/ssangyong/rexton', loadChildren: () => import('./views/client/Pieces/voiture/ssangyong/rexton/rexton.module').then(m => m.RextonModule)  },
   { path: 'voiture/ssangyong/trivoli', loadChildren: () => import('./views/client/Pieces/voiture/ssangyong/trivoli/trivoli.module').then(m => m.TrivoliModule)  },
   { path: 'voiture/volkswagen/golf1/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/volkswagen/golf1/golf1.module').then(m => m.Golf1Module)  },
   { path: 'voiture/volkswagen/golf2/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/volkswagen/golf2/golf2.module').then(m => m.Golf2Module)  },
   { path: 'voiture/volkswagen/golf3/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/volkswagen/golf3/golf3.module').then(m => m.Golf3Module)  },
   { path: 'voiture/volkswagen/golf4/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/volkswagen/golf4/golf4.module').then(m => m.Golf4Module)  },
   { path: 'voiture/volkswagen/golf5/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/volkswagen/golf5/golf5.module').then(m => m.Golf5Module)  },
   { path: 'voiture/volkswagen/golf6/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/volkswagen/golf6/golf6.module').then(m => m.Golf6Module)  },
   { path: 'voiture/volkswagen/golf7/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/volkswagen/golf7/golf7.module').then(m => m.Golf7Module)  },
   { path: 'voiture/volkswagen/golf8/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/volkswagen/golf8/golf8.module').then(m => m.Golf8Module)  },
   { path: 'voiture/volkswagen/amarok/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/volkswagen/amarok/amarok.module').then(m => m.AmarokModule)  },
   { path: 'voiture/volkswagen/jeta/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/volkswagen/jeta/jeta.module').then(m => m.JetaModule)  },
   { path: 'voiture/volkswagen/touareg/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/volkswagen/touareg/touareg.module').then(m => m.TouaregModule)  },
   { path: 'voiture/volkswagen/passat/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/volkswagen/passat/passat.module').then(m => m.PassatModule)  },
   { path: 'voiture/volkswagen/tiguan/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/volkswagen/tiguan/tiguan.module').then(m => m.TiguanModule)  },
   { path: 'voiture/bmw/serie6/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/bmw/serie6/serie6.module').then(m => m.Serie6Module)  },
   { path: 'voiture/bmw/x1/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/bmw/x1/x1.module').then(m => m.X1Module)  },
   { path: 'voiture/bmw/x2/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/bmw/x2/x2.module').then(m => m.X2Module)  },
   { path: 'voiture/bmw/x3/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/bmw/x3/x3.module').then(m => m.X3Module)  },
   { path: 'voiture/bmw/x4/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/bmw/x4/x4.module').then(m => m.X4Module)  },
   { path: 'voiture/bmw/x5/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/bmw/x5/x5.module').then(m => m.X5Module)  },
   { path: 'voiture/mercedes/gla/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/mercedes/gla/gla.module').then(m => m.GlaModule)  },
   { path: 'voiture/mercedes/glc/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/mercedes/glc/glc.module').then(m => m.GlcModule)  },
   { path: 'voiture/mercedes/classea/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/mercedes/classea/classea.module').then(m => m.ClasseaModule)  },
   { path: 'voiture/mercedes/classeg/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/mercedes/classeg/classeg.module').then(m => m.ClassegModule)  },
   { path: 'voiture/mercedes/classes/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/mercedes/classes/classes.module').then(m => m.ClassesModule)  },
   { path: 'voiture/seat/ateca/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/seat/ateca/ateca.module').then(m => m.AtecaModule)  },
   { path: 'voiture/seat/arona/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/seat/arona/arona.module').then(m => m.AronaModule)  },
   { path: 'voiture/seat/ibiza/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/seat/ibiza/ibiza.module').then(m => m.IbizaModule)  },
   { path: 'voiture/seat/leon/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/seat/leon/leon.module').then(m => m.LeonModule)  },
   { path: 'voiture/skoda/superb/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/skoda/superb/superb.module').then(m => m.SuperbModule)  },
   { path: 'voiture/skoda/kushaq/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/skoda/kushaq/kushaq.module').then(m => m.KushaqModule)  },
   { path: 'voiture/skoda/kodiaq/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/skoda/kodiaq/kodiaq.module').then(m => m.KodiaqModule)  },
   { path: 'voiture/skoda/fabia/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/skoda/fabia/fabia.module').then(m => m.FabiaModule)  },
   { path: 'voiture/renault/cliocampus/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/renault/cliocampus/cliocampus.module').then(m => m.CliocampusModule)  },
   { path: 'voiture/renault/cliodynamique/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/renault/cliodynamique/cliodynamique.module').then(m => m.CliodynamiqueModule)  },
   { path: 'voiture/renault/megane/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/renault/megane/megane.module').then(m => m.MeganeModule)  },
   { path: 'voiture/renault/symbole/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/renault/symbole/symbole.module').then(m => m.SymboleModule)  },
   { path: 'voiture/renault/clio3/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/renault/clio3/clio3.module').then(m => m.Clio3Module)  },
   { path: 'voiture/peugeot/p206/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/peugeot/p206/p206.module').then(m => m.P206Module)  },
   { path: 'voiture/peugeot/p308/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/peugeot/p308/p308.module').then(m => m.P308Module)  },

   { path: 'voiture/peugeot/p408/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/peugeot/p408/p408.module').then(m => m.P408Module)  },
   { path: 'voiture/peugeot/p3008/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/peugeot/p3008/p3008.module').then(m => m.P3008Module)  },
   { path: 'voiture/fiat/tipo/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/fiat/tipo/tipo.module').then(m => m.TipoModule)  },
   { path: 'voiture/fiat/punto/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/fiat/punto/punto.module').then(m => m.PuntoModule)  },
   { path: 'voiture/fiat/panda/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/fiat/panda/panda.module').then(m => m.PandaModule)  },
   { path: 'voiture/fiat/fiorino/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/fiat/fiorino/fiorino.module').then(m => m.FiorinoModule)  },
   { path: 'voiture/fiat/f500/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/fiat/f500/f500.module').then(m => m.F500Module)  },
   { path: 'voiture/kia/sorento/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/kia/sorento/sorento.module').then(m => m.SorentoModule)  },
   { path: 'voiture/kia/xceed/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/kia/xceed/xceed.module').then(m => m.XceedModule)  },
   { path: 'voiture/kia/sportage/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/kia/sportage/sportage.module').then(m => m.SportageModule)  },
   { path: 'voiture/kia/rio/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/kia/rio/rio.module').then(m => m.RioModule)  },
   { path: 'voiture/toyota/aygo/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/toyota/aygo/aygo.module').then(m => m.AygoModule)  },
   { path: 'voiture/toyota/rav4/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/toyota/rav4/rav4.module').then(m => m.Rav4Module)  },
   { path: 'voiture/toyota/yaris/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/toyota/yaris/yaris.module').then(m => m.YarisModule)  },
   { path: 'voiture/toyota/hilux/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/toyota/hilux/hilux.module').then(m => m.HiluxModule)  },
   { path: 'voiture/toyota/chr/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/toyota/chr/chr.module').then(m => m.ChrModule)  },
   { path: 'voiture/audi/q5/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/audi/q5/q5.module').then(m => m.Q5Module)  },
   { path: 'voiture/audi/a4/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/audi/a4/a4.module').then(m => m.A4Module)  },
   { path: 'voiture/audi/a6/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/audi/a6/a6.module').then(m => m.A6Module)  },
   { path: 'voiture/audi/a3/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/audi/a3/a3.module').then(m => m.A3Module)  },
   { path: 'voiture/citroen/c5/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/citroen/c5/c5.module').then(m => m.C5Module)  },
   { path: 'voiture/citroen/celysee/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/citroen/celysee/celysee.module').then(m => m.CelyseeModule)  },

   { path: 'voiture/citroen/berlingo/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/citroen/berlingo/berlingo.module').then(m => m.BerlingoModule)  },
   { path: 'voiture/citroen/c3/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/citroen/c3/c3.module').then(m => m.C3Module)  },
   { path: 'voiture/hyundai/i10/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/hyundai/i10/i10.module').then(m => m.I10Module)  },
   { path: 'voiture/hyundai/i20/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/hyundai/i20/i20.module').then(m => m.I20Module)  },
   { path: 'voiture/honda/city/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/honda/city/city.module').then(m => m.CityModule)  },
   { path: 'voiture/honda/crv/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/honda/crv/crv.module').then(m => m.CrvModule)  },
   { path: 'voiture/ssangyong/korando/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/ssangyong/korando/korando.module').then(m => m.KorandoModule)  },
   { path: 'voiture/ssangyong/rexton/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/ssangyong/rexton/rexton.module').then(m => m.RextonModule)  },
   { path: 'voiture/ssangyong/musso/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/ssangyong/musso/musso.module').then(m => m.MussoModule)  },
   { path: 'voiture/ssangyong/trivoli/pieces/:id', loadChildren: () => import('./views/client/detaillep/voiture/ssangyong/trivoli/trivoli.module').then(m => m.TrivoliModule)  },
   { path: 'moto', loadChildren: () => import('./views/client/moto/moto.module').then(m => m.MotoModule)  },
   { path: 'moto/yamaha', loadChildren: () => import('./views/client/Modele/yamaha/yamaha.module').then(m => m.YamahaModule)  },
   { path: 'moto/kawasaki', loadChildren: () => import('./views/client/Modele/kawasaki/kawasaki.module').then(m => m.KawasakiModule)  },
   { path: 'moto/yamaha/mt03', loadChildren: () => import('./views/client/Pieces/moto/yamaha/mt03/mt03.module').then(m => m.Mt03Module)  },
   { path: 'moto/yamaha/tmax', loadChildren: () => import('./views/client/Pieces/moto/yamaha/tmax/tmax.module').then(m => m.TmaxModule)  },
   { path: 'moto/yamaha/mt03/pieces/:id', loadChildren: () => import('./views/client/detaillep/moto/yamaha/mt03/mt03.module').then(m => m.Mt03Module)  },
   { path: 'moto/yamaha/tmax/pieces/:id', loadChildren: () => import('./views/client/detaillep/moto/yamaha/tmax/tmax.module').then(m => m.TmaxModule)  },
   { path: 'moto/kawasaki/z1000', loadChildren: () => import('./views/client/Pieces/moto/kawasaki/z1000/z1000.module').then(m => m.Z1000Module)  },
   { path: 'moto/kawasaki/z750', loadChildren: () => import('./views/client/Pieces/moto/kawasaki/z750/z750.module').then(m => m.Z750Module)  },
   { path: 'moto/kawasaki/z1000/pieces/:id', loadChildren: () => import('./views/client/detaillep/moto/kawasaki/z1000/z1000.module').then(m => m.Z1000Module)  },
   { path: 'moto/kawasaki/z750/pieces/:id', loadChildren: () => import('./views/client/detaillep/moto/kawasaki/z750/z750.module').then(m => m.Z750Module)  },

 ] },
 
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
